name: CI

on:
  push:
    branches:
      - main
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/devops/requirements.txt
    - name: Run CI test
      run: ./scripts/devops/unit.sh
    - name: Run smoke test
      run: ./scripts/devops/smoke.sh