name: "Unit Tests"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/devops/requirements.txt

      - name: Unit Test
        run: ./scripts/devops/unit.sh